[package]
name = "pg_pitr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
anyhow = "1.0.91"
zstd = "0.13.2"
blake3 = "1.5.4"
log = "0.4.22"
env_logger = "0.11.5"
humantime = "2.1.0"
tar = "0.4.42"
